FROM docker:17.03.1-ce

ENV DOCKERCOMPOSE_VERSION=1.14.0

RUN apk add --update python3 && \
    python3 -m ensurepip --upgrade && \
    pip3 install docker-compose==${DOCKERCOMPOSE_VERSION} && \
    rm -rf /var/cache/apk/*

RUN docker-compose -v