FROM docker:18.03.1-ce-dind

ENV DOCKERCOMPOSE_VERSION=1.21.2

RUN apk add --update python3 && \
    python3 -m ensurepip --upgrade && \
    pip3 install docker-compose==${DOCKERCOMPOSE_VERSION} && \
    rm -rf /var/cache/apk/*

RUN docker-compose -v